In [43]:
import pandas as pd

In [44]:
df = pd.read_csv('telur_ayam_ras_random_submission_new.csv')
df

                                          id         price
0               Bawang Merah/Aceh/2024-10-01  25064.517897
1               Bawang Merah/Aceh/2024-10-02  25052.469742
2               Bawang Merah/Aceh/2024-10-03  25063.953955
3               Bawang Merah/Aceh/2024-10-04  25076.740636
4               Bawang Merah/Aceh/2024-10-05  25042.237867
...                                      ...           ...
3123  Bawang Merah/Sumatera Utara/2024-12-27  25035.127490
3124  Bawang Merah/Sumatera Utara/2024-12-28  25038.817469
3125  Bawang Merah/Sumatera Utara/2024-12-29  25053.970254
3126  Bawang Merah/Sumatera Utara/2024-12-30  25007.435154
3127  Bawang Merah/Sumatera Utara/2024-12-31  25064.313550

[3128 rows x 2 columns]

In [45]:
df["id"] = df["id"].str.replace("Bawang Merah", "Telur Ayam Ras", regex=False)
df

                                            id         price
0               Telur Ayam Ras/Aceh/2024-10-01  25064.517897
1               Telur Ayam Ras/Aceh/2024-10-02  25052.469742
2               Telur Ayam Ras/Aceh/2024-10-03  25063.953955
3               Telur Ayam Ras/Aceh/2024-10-04  25076.740636
4               Telur Ayam Ras/Aceh/2024-10-05  25042.237867
...                                        ...           ...
3123  Telur Ayam Ras/Sumatera Utara/2024-12-27  25035.127490
3124  Telur Ayam Ras/Sumatera Utara/2024-12-28  25038.817469
3125  Telur Ayam Ras/Sumatera Utara/2024-12-29  25053.970254
3126  Telur Ayam Ras/Sumatera Utara/2024-12-30  25007.435154
3127  Telur Ayam Ras/Sumatera Utara/2024-12-31  25064.313550

[3128 rows x 2 columns]

In [46]:
df.to_csv('telur_ayam_ras_random_submission_new.csv', index=False)